// <auto-generated />
using AluraPlayList.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AluraPlayList.Migrations
{
  [DbContext(typeof(AppDbContext))]
  [Migration("20221027235010_Video entity")]
  partial class Videoentity
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
          .HasAnnotation("ProductVersion", "6.0.10")
          .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("Video", b =>
          {
            b.Property<int>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("int");

            b.Property<string>("Description")
                      .IsRequired()
                      .HasMaxLength(5000)
                      .HasColumnType("varchar(5000)");

            b.Property<string>("Title")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.Property<string>("Url")
                      .IsRequired()
                      .HasMaxLength(100)
                      .HasColumnType("varchar(100)");

            b.HasKey("Id");

            b.ToTable("Videos");
          });
#pragma warning restore 612, 618
    }
  }
}
